### ISSUE TITLE
访达边栏图标

### ISSUE THREAD

**Issue by hiltonjiang** [lemon4ex/iRightMenu-issues#1]
您好，感谢开发此应用！在使用的过程中我发现一个小问题（[Openinterminal.app](https://github.com/Ji4n1ng/OpenInTerminal)也有同样的问题）

开启扩展后访达左侧边栏上移动硬盘的图标会变成这样
<img width="31" alt="image" src="https://user-images.githubusercontent.com/30884730/165802629-a05f0e5a-cce2-4e25-98b4-252f43c30b0e.png">
如果关闭扩展，则会变成本来的样子
<img width="31" alt="image" src="https://user-images.githubusercontent.com/30884730/165802802-7335a26b-e915-437d-bcc8-da38bd614326.png">

**Comment by lemon4ex** [comment]
感谢反馈。
开启Finder拓展后出现外接磁盘图标不正常的问题可能是macOS的一个bug，只能等待苹果修复。
目前已知 10.15 ~ 12 系统都有这个问题。
IRightMenu的右键菜单支持在外接磁盘上使用，而启用上述功能后就会引发外接磁盘图标不正常的问题。
目前有一个绕过的方法，那就是在外接磁盘上不启用iRightMenu。这个开关功能目前还没有，后续会增加。

**Comment by lemon4ex** [comment]
v1.1.2版本在更多功能页增加了是否在外界磁盘启用右键菜单的选项，请更新验证，感谢。
