### ISSUE TITLE
能否添加一个新建文件夹的按钮

### ISSUE THREAD

**Issue by chenxyhz** [lemon4ex/iRightMenu-issues#10]
因为在某些情况下,系统自带的新建文件夹是不显示的,如:当目录是列表模式显示,文件比较多满屏情况,这样右键是不显示新建文件夹的
![WX20230509-094241@2x](https://user-images.githubusercontent.com/15242184/236973118-99b68c2f-dbbc-4ac6-b386-dfe07bef456b.png)

**Comment by lemon4ex** [comment]
后面会考虑是否添加，个人建议使用系统自带的快捷键 `Command + Shift + N` 来创建文件夹，非常方便。

**Comment by lemon4ex** [comment]
v1.1.6版本已添加新建文件夹菜单，请及时更新体验。
