### ISSUE TITLE
右键进入alacritty

### ISSUE THREAD

**Issue by AndyJado** [lemon4ex/iRightMenu-issues#11]

**Comment by lemon4ex** [comment]
alacritty没有提供直接使用路径打开的服务，上架的版本由于App Store的审核原因不支持使用命令行来调用alacritty，无法增加该功能。
[iRightMenu Pro](https://byteage.com/store/24.html)是iRightMenu的专业版本，没有上架，权限更多，真正支持使用脚本作为菜单，功能更强大，可以很好的满足你的需求。支持7天试用，你可以使用一下。
