### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by xiaooojun** [lemon4ex/iRightMenu-issues#12]
能给其他应用程序右键新增功能吗

**Comment by lemon4ex** [comment]
何解？可以在仿达的右键菜单上增加使用指定应用打开文件。猜你是说给其他程序内部的右键菜单增加功能？

**Comment by xiaooojun** [comment]
是的 我研究了下，，应该不可以，，是想表达给其他应用添加右键自定义功能
