### ISSUE TITLE
OneDrive路径下无发显示右键扩展菜单

### ISSUE THREAD

**Issue by virologist** [lemon4ex/iRightMenu-issues#18]
Mac：M1最新操作系统版本14.3.1
软件是app商店下周的最新版

在是在进入onedrive文件路径以前的截图：可以显示
<img width="267" alt="image" src="https://github.com/lemon4ex/iRightMenu-issues/assets/54756814/d1ab259b-b874-4276-8078-95a47d2d61f3">

这是在进入OneDrive路径文件后的截图：未显示
<img width="506" alt="image" src="https://github.com/lemon4ex/iRightMenu-issues/assets/54756814/fa559162-84af-406b-a8dd-edd7e0f8ccd1">

**Comment by lemon4ex** [comment]
苹果在macOS 13.x以后，不支持在实现了FileProvider的文件夹中显示Finder右键拓展菜单，详情讨论请移步到 #6
