### ISSUE TITLE
英语化

### ISSUE THREAD

**Issue by UndertaleAlphys** [lemon4ex/iRightMenu-issues#2]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/90361250/171983477-62ffb729-0a16-474c-b344-9aef5f5ff7b4.png">
软件不错，有些没有完全英语化。“主菜单”和右键里的“其他菜单”看着有点尴尬

**Comment by lemon4ex** [comment]
感谢反馈，后续更新会修复。

**Comment by lemon4ex** [comment]
v1.1.2版本已完善，请更新重启访达后再试。
