### ISSUE TITLE
在macOS 15上无法工作

### ISSUE THREAD

**Issue by KarryCharon** [lemon4ex/iRightMenu-issues#20]
最新的15版系统上, 无法为iRightMenu设置访达权限

**Comment by KarryCharon** [comment]
![QQ_1724663623008](https://github.com/user-attachments/assets/dfb7e257-17e7-435d-988f-7dbf57cc091f)

**Comment by lemon4ex** [comment]
15系统已经没有启用插件的入口了，要启用插件，可以按照下面的方法手动启用：

打开终端，执行下面的命令：

`pluginkit -mAD -p com.apple.FinderSync -vvv`

搜索 `net.ymlab.iRightMenu` 找到 `iRightMenu` 的插件项，输出大致如下:

```
net.ymlab.iRightMenu.iRightMenuPlugin(1.1.7)
	            Path = /Applications/iRightMenu.app/Contents/PlugIns/iRightMenuPlugin.appex
	            UUID = 5FAC3AAE-D98E-42F6-9622-9FCE6749038C
	       Timestamp = 2023-09-23 09:27:45 +0000
	             SDK = com.apple.FinderSync
	   Parent Bundle = /Applications/iRightMenu.app
	    Display Name = iRightMenu
	      Short Name = iRightMenu
	     Parent Name = iRightMenu
	        Platform = macOS
```

得到 UUID = `5FAC3AAE-D98E-42F6-9622-9FCE6749038C`

然后继续在终端输入下面的命令，启用插件：

`pluginkit -e "use" -u "5FAC3AAE-D98E-42F6-9622-9FCE6749038C"`

-u 后面的参数是刚刚获取到的插件的 UUID

**Comment by lemon4ex** [comment]
如果出现访问文件弹窗需要授权，但是点击弹窗的任何位置弹窗都消失的问题，尝试先手动打开 iRightMenu 主窗口后再进行操作
![a3a2afcd23894bfdea634312dded7eba](https://github.com/user-attachments/assets/614fd549-99ca-4271-9952-84cd9c5c924e)
感谢群友 @键盘侠●MYW 反馈

**Comment by KarryCharon** [comment]
> 如果出现访问文件弹窗需要授权，但是点击弹窗的任何位置弹窗都消失的问题，尝试先手动打开 iRightMenu 主窗口后再进行操作 ![a3a2afcd23894bfdea634312dded7eba](https://private-user-images.githubusercontent.com/7862040/363542529-614fd549-99ca-4271-9952-84cd9c5c924e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDUwMjUsIm5iZiI6MTcyNTI0NDcyNSwicGF0aCI6Ii83ODYyMDQwLzM2MzU0MjUyOS02MTRmZDU0OS05OWNhLTQyNzEtOTk1Mi04NGNkOWM1YzkyNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDIzODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEwMDEwMWFlZmFjNmVhOGE3ZjBiMDllNjhiZDRhYmY4OGJhNGJhOTJhMTkzZjI0ODI2NTdlMjE2MGIyMDA4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OcN09eV-94aTgwnrvJzYBlysGomwgjtjZaVDIhlNeLk) 感谢群友 @键盘侠●MYW 反馈

感谢! 已解决!

**Comment by Arcadi4** [comment]
> 如果出现访问文件弹窗需要授权，但是点击弹窗的任何位置弹窗都消失的问题，先把获取权限那个界面关掉，然后把 iRightMenu的设置界面调出来，然后再去尝试获取权限那步 ![a3a2afcd23894bfdea634312dded7eba](https://private-user-images.githubusercontent.com/7862040/363542529-614fd549-99ca-4271-9952-84cd9c5c924e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODQ2NjcsIm5iZiI6MTczMTI4NDM2NywicGF0aCI6Ii83ODYyMDQwLzM2MzU0MjUyOS02MTRmZDU0OS05OWNhLTQyNzEtOTk1Mi04NGNkOWM1YzkyNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDAxOTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhlMGNiNWFmZTE0ZTdlYmM5MWJiMWFiZTc0ZjU2NmE1NWE5NmY3YzRlMDE3Zjc3ODI5OGNlNDVjMWQ0ZGYxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1dG0ymvRqOo908NbKC_Cv5BkaeE-4vdEqjfZ3uHh6xg) 感谢群友 @键盘侠●MYW 反馈

解决了，感谢！可以考虑写在README或者软件帮助中？
