### ISSUE TITLE
目录层级中有空格的话，进入终端选项会打开两个窗口

### ISSUE THREAD

**Issue by ripp1e** [lemon4ex/iRightMenu-issues#4]
比如，当前目录为/home/123/Downloads/abc def/g/  ，并且，存在/home/123/Downloads/abc/目录，在../g/ 目录下使用右键菜单进入终端的选项的时候会打开定位在，/abc/和/g/两个窗口。

**Comment by lemon4ex** [comment]
感谢反馈，1.1.4版本已修复，在App Store下载更新一下试试。
